@extends('layouts.investigator')

@section('content')
<style>
     .breadcrumb-bar {
        margin-top: -20px;
        margin-left: 2rem;
        margin-bottom: 1.5rem;
    }
    body {
        font-family: 'Segoe UI', sans-serif;
        color: #333;
    }

    .report-container {
        background-color: #ffffff;
        padding: 2rem;
        border-radius: 10px;
        box-shadow: 0 0 25px rgba(0, 123, 255, 0.1);
    }

    .report-header {
        border-bottom: 2px solid #87CEEB;
        margin-bottom: 1.5rem;
        padding-bottom: 1rem;
    }

    .section-title {
        background-color: #87CEEB;
        color: #fff;
        padding: 0.75rem 1.25rem;
        font-weight: bold;
        border-radius: 5px 5px 0 0;
    }

    .section-body {
        background-color: #f7faff;
        padding: 1.25rem;
        border: 1px solid #dce9f9;
        border-top: none;
        margin-bottom: 2rem;
        border-radius: 0 0 5px 5px;
    }

    .text-label {
        font-weight: 600;
    }

    .btn-sky {
        background-color: #87CEEB;
        color: #fff;
        border: none;
    }

    .btn-sky:hover {
        background-color: #6db9d6;
        color: #fff;
    }

    hr {
        border-color: #cbe2f9;
    }
</style>
<div class="container py-5">
    <!-- Breadcrumb -->
    <div class="breadcrumb-bar">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="{{ url('investigator/dash') }}"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="{{ url('investigator/assign') }}">Assigned Cases</a></li>
                <li class="breadcrumb-item active" aria-current="page"> Case Report</li>
            </ol>
        </nav>
    </div>

<div class="container py-5 report-container">

    {{-- Export PDF --}}
    <div class="text-end mb-4">
        <a href="{{ route('investigator.cases.report.pdf', $case->case_id) }}" class="btn btn-sky">
            <i class="fas fa-file-pdf me-1"></i> Download PDF
        </a>
    </div>

    {{-- Report Header --}}
    <div class="report-header">
        <h3 class="text-primary">Investigator Report – Case {{ $case->case_number }}</h3>
        <p><span class="text-label">Date:</span> {{ now()->format('Y-m-d') }}</p>
        <p><span class="text-label">Time:</span> {{ now()->format('H:i') }}</p>
        <p><span class="text-label">Generated By:</span> {{ $user->fname }} {{ $user->sname }}</p>
    </div>

    {{-- Complaint Statement --}}
    <div>
        <div class="section-title">Complaint Statement ({{ $complaint->sname }})</div>
        <div class="section-body">
            {!! $complaint->statement !!}
        </div>
    </div>

    {{-- Suspect Statements --}}
    <div>
        <div class="section-title">Suspect Statements</div>
        <div class="section-body">
            @if($suspects->isNotEmpty())
                @foreach($suspects as $suspect)
                    <div class="mb-4">
                        <h6 class="fw-bold">({{ $suspect->fname }} {{ $suspect->sname }})</h6>
                        {!! $suspect->statement !!}
                        <hr>
                    </div>
                @endforeach
            @else
                <p class="text-muted">No suspect statements available.</p>
            @endif
        </div>
    </div>

    {{-- Investigation Progress --}}
    <div>
        <div class="section-title">Investigation Progress</div>
        <div class="section-body">
            @forelse($progress as $entry)
                <div class="mb-4">
                    <p class="mb-1 text-muted">
                        <strong>{{ \Carbon\Carbon::parse($entry->date)->format('d M Y H:i') }}</strong>
                        @if(!empty($entry->entry_type))
                            <span class="badge bg-secondary">{{ ucfirst($entry->entry_type) }}</span>
                        @endif
                    </p>
                    {!! $entry->notes !!}
                    <hr>
                </div>
            @empty
                <p class="text-muted">No progress updates available.</p>
            @endforelse
        </div>
    </div>

    {{-- Case Closure --}}
    <div>
        <div class="section-title">Case Closure Statement</div>
        <div class="section-body">
            @if($closure)
                <p><strong>Type:</strong> {{ $closure->closure_type }}</p>
                <p><strong>Date:</strong> {{ \Carbon\Carbon::parse($closure->closure_date)->format('d M Y') }}</p>
                {!! $closure->reason !!}
            @else
                <p class="text-muted">No closure statement available.</p>
            @endif
        </div>
    </div>

</div>
@endsection
